### ISSUE TITLE
Conection wifi

### ISSUE THREAD

**Issue by voricente** [octalparrot/ph-cl-astralpool-modbus#1]
Hi,

I would like to connect the modbus to my raspberry by wifi. Do you recommend any device to do it? What would I have to modify in your script? 

Thank you very much.

**Comment by voricente** [comment]
Hi again,
I buy a RS485 to WI-FI for send MODBUS from Astralpool and with your scrip, don't receved anything.
Could you help me?
Thanks

**Comment by octalparrot** [comment]
what module did you buy?

**Comment by voricente** [comment]
This one: https://a.aliexpress.com/_EvnJc2h

**Comment by octalparrot** [comment]
have you checked the modbus settings (channel, transmission) on the astralpool controller, and you used the same settings in rs485 - wifi module?

**Comment by voricente** [comment]
![Captura de pantalla 2022-11-26 a las 19 19 12](https://user-images.githubusercontent.com/84455018/204103367-9b0865c2-9f87-4e46-91f1-d4642da79303.png)
![Captura de pantalla 2022-11-26 a las 19 19 25](https://user-images.githubusercontent.com/84455018/204103368-836c9848-7b90-4b22-8418-0cd6a49bdc3a.png)

I think so

**Comment by octalparrot** [comment]
Ok, show me your settings from astralpool controller (networking, rate, stop bits)

**Comment by voricente** [comment]
![Captura de pantalla 2022-11-26 a las 19 21 43](https://user-images.githubusercontent.com/84455018/204103450-4164e01d-e8cc-48b7-b4c2-cb3b046de61d.png)
 I used this one

**Comment by octalparrot** [comment]
try:

> modpoll -m tcp 192.168.1.43 -0 -1 -a 1 -t4 -r 35
or

> modpoll -m enc 192.168.1.43 -0 -1 -a 1 -t4 -r 35

**Comment by voricente** [comment]
And the result is:

![Captura de pantalla 2022-11-26 a las 19 24 01](https://user-images.githubusercontent.com/84455018/204103545-b6dff51a-35e8-433c-b509-9889b8844ae9.png)

**Comment by octalparrot** [comment]
ok, you don't have a modpoll command installed :)

**Comment by octalparrot** [comment]
https://www.modbusdriver.com/modpoll.html

**Comment by voricente** [comment]
Thanks.
I'll try it tomorrow and post the result.

**Comment by voricente** [comment]
I use NODE-RED, do you think it would be possible to integrate it?

**Comment by voricente** [comment]
Any idea?
![Captura de pantalla 2022-11-27 a las 13 46 07](https://user-images.githubusercontent.com/84455018/204135974-3087e7e5-90ab-4466-b03f-af136cb61101.png)

Thanks

**Comment by octalparrot** [comment]
What about -m enc instead of -m tcp?

W dniu 27.11.2022 o 13:46, voricente pisze:

**Comment by voricente** [comment]
Take a look
![Captura de pantalla 2022-11-27 a las 13 50 28](https://user-images.githubusercontent.com/84455018/204136147-8345c1e0-26c2-4e3e-b840-3d6b0a49988e.png)

**Comment by octalparrot** [comment]
try modpoll -m enc -0 -1 -a 1 -t4 -r 35 192.168.1.43

W dniu 27.11.2022 o 13:51, voricente pisze:

**Comment by voricente** [comment]
![Captura de pantalla 2022-11-27 a las 13 53 03](https://user-images.githubusercontent.com/84455018/204136273-c57d9737-ae96-4218-99d6-2918ce659ecf.png)

**Comment by octalparrot** [comment]
no answer from controller, you checked settings in network on astralpool 
controller?

W dniu 27.11.2022 o 13:53, voricente pisze:

**Comment by voricente** [comment]
I don't know it

**Comment by voricente** [comment]
The rs485-wifi is conected
![Captura de pantalla 2022-11-27 a las 13 58 07](https://user-images.githubusercontent.com/84455018/204136463-7de3d430-7ca6-4125-927b-b0c5ad618a24.png)

**Comment by octalparrot** [comment]
please post a photo from:
astralpool controller
connection controller
connection rs485-wifi module

W dniu 27.11.2022 o 13:57, voricente pisze:

**Comment by octalparrot** [comment]
astralpool default settings from manual are:
19200 parity even
you must match same settings on the controller and the rs485 module

W dniu 27.11.2022 o 13:58, voricente pisze:

**Comment by voricente** [comment]
![IMG_0925](https://user-images.githubusercontent.com/84455018/204136971-ab372d5e-fe8a-4405-88bc-bb1e7e9b3032.jpg)
![IMG_0926](https://user-images.githubusercontent.com/84455018/204136973-0a39b4de-579a-4ef7-96f7-060e6bc90202.jpg)
![IMG_0929](https://user-images.githubusercontent.com/84455018/204136974-f38cf2be-9b15-4622-ad2e-31cf7cdcc08c.jpg)
![Captura de pantalla 2022-11-27 a las 14 06 41](https://user-images.githubusercontent.com/84455018/204136977-ca406159-4570-4b63-ace7-4d045b82e626.png)

**Comment by octalparrot** [comment]
What is the controller model?

**Comment by voricente** [comment]
The controller model?
This one? Elfin-EW11?

**Comment by voricente** [comment]
Astralpool Smart Next?

**Comment by voricente** [comment]
![Captura de pantalla 2022-11-27 a las 14 30 35](https://user-images.githubusercontent.com/84455018/204138103-35083753-73ec-45b1-a686-920d92096001.png)

I read something!!!

**Comment by voricente** [comment]
I have this but I can't know what it means because in the Astralpool panel, the numbers are diferent


![Captura de pantalla 2022-11-27 a las 14 52 28](https://user-images.githubusercontent.com/84455018/204138936-385a38cb-f905-4269-b7fa-386a1f4da986.png)

**Comment by octalparrot** [comment]
mine is like this:
https://www.astralpool.com/en/en/water-treatment-equipment/dosing-systems/automatic-regulation/controller.html

**Comment by voricente** [comment]
Ops.... Do you know where we can find de adress of MODBUS TCP AstralPool?

**Comment by octalparrot** [comment]
Maybe this is it?
[62185355.pdf](https://github.com/octalparrot/ph-cl-astralpool-modbus/files/10103895/62185355.pdf)

**Comment by voricente** [comment]
MODBUS RTU?

I find adress 65 is the power of the electrolisis and 87 is the PH set/100  


![Captura de pantalla 2022-11-28 a las 14 41 02](https://user-images.githubusercontent.com/84455018/204292011-8b754432-c99e-4213-b6c8-73d2d8d44623.png)
